version: "3"
services:
  app:
    image: chrome:v1 # webrtc:v6 #app:v4
    environment:
      - DISPLAY=:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    runtime: nvidia
